apiVersion: v2
name: mlflow
description: |
  [MLFlow](https://mlflow.org/) is an open source platform specialized in tracking ML experiments, and packaging and deploying ML models.
maintainers:
  - email: ursu.ciprian.petru@gmail.com
    name: Ciprian Ursu 
type: application
version: 1.0.0
appVersion: 1.20.2