{{- if .Values.secrets.store.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ template "mlflow.fullname" . }}-secrets
  labels:
    app: {{ template "mlflow.fullname" . }}
    chart: {{ template "mlflow.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  provider: {{ .Values.secrets.store.provider }}
  secretObjects:
    - secretName: mlflow-db-user-password  # the k8s secret name
      type: Opaque
      data:
        - objectName: "mlflow-tracking-server-password"  # reference the corresponding parameter
          key: mlflow-db-password
    - secretName: mlflow-db-master-password
      type: Opaque
      data:
        - objectName: "rds-mlflow-tracking-server-dev-master-password"
          key: mlflow-db-master-password
  parameters:
    objects: |
      - objectName: "mlflow-tracking-server-password"  # the AWS secret name 
        objectType: "secretsmanager"
      - objectName: "rds-mlflow-tracking-server-dev-master-password"
        objectType: "secretsmanager"
{{- end }}