apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-env
  labels:
    app: {{ template "mlflow.fullname" . }}
    chart: {{ template "mlflow.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
type: Opaque
data:
    DB_HOST: {{ .Values.mlflowBackend.connections.db_host | b64enc | quote }}
    DB_PORT: {{ .Values.mlflowBackend.connections.db_port | b64enc | quote }}
    DB_USER: {{ .Values.mlflowBackend.connections.db_user | b64enc | quote }}
    DB_NAME: {{ .Values.mlflowBackend.connections.db_name | b64enc | quote }}
